<?php
$order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);
if ($order->getCustomerId()) {
    $email = $order->getCustomerEmail(); //logged in customer
} else {
    $email = $order->getBillingAddress()->getEmail(); //not logged in customer
}
$price = $order->getGrandTotal();
$currency = Mage::app()->getStore()->getCurrentCurrencyCode();
if (file_exists(MAGENTO_ROOT . '/data/currencies.json')) {
    $currency_json_data = json_decode(file_get_contents(MAGENTO_ROOT . '/data/currencies.json'), 1);
    $checkoutData['currency_multiplier'] = floatval($currency_json_data[$currency]);
} else {
    $checkoutData['currency_multiplier'] = floatval(100);
}
$new_price = $checkoutData['currency_multiplier'] * $price;
$payment = $order->getPayment();
$method = $payment->getMethodInstance();
if ($method->getConfigData('test_mode') == 1) {
    $key = $method->getConfigData('test_open_key');
} else {
    $key = $method->getConfigData('live_open_key');
}
?>
<h2 style="background-color: #3399CC;padding: 10px;color: #fff;margin-right: 10px"><?php echo $this->__('Start Payment Gateway') ?></h2>
<form id= 'payfortstartform' method="post" action="<?php echo Mage::helper('payfortstartgateway')->getPaymentGatewayUrl(); ?>">
    <script src="https://beautiful.start.payfort.com/checkout.js"
            data-key="<?php echo $key; ?>"
            data-currency="<?php echo $currency; ?>"
            data-amount= "<?php echo $new_price; ?>"
            data-email= "<?php echo $email; ?>">
    </script>
</form>
<script>
    jQuery("#payfortstartform").find("button").trigger("click");
</script>